[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "https://racketradar.onrender.com/:splat"
  status = 301
  force = true
  headers = {X-From = "Netlify"}